### ISSUE TITLE
Windows函数地址定位

### ISSUE THREAD

**Issue by xbstory** [KevinsBobo/frida_usage_record#1]
一般是怎么定位被调用函数的地址的呢？

这里的address 
new NativeFunction(ptr(address))

有没有什么技巧或者教程可以推荐一下吗？

**Comment by KevinsBobo** [comment]
这个属于逆向调试的范畴，书籍推荐《c++反汇编与逆向分析技术揭秘》、《加密解密（第四版）》，同时也推荐看雪论坛的精华、优秀文章。

**Comment by xbstory** [comment]
感谢回复
